import PagesHeader from "@/components/header-other-pages";
import PagesHeaderTransparent from "@/components/header-other-pages-transparent";
import Image from "next/image";



export const metadata = {
    title: "Introduce projects",
    description: "Generated by create next app",
};



function Projects() {


    return (
        <>
            {/* <div className="w-full max-h-screen mb-[50px]"> */}
                
                <div className="w-full h-[200px] md:h-[600px] text-white bg-[url(/images/img/project-6.jpg)] bg-no-repeat bg-cover">
                <PagesHeaderTransparent />
                </div>
            {/* </div> */}

            <div className="w-full min-h-screen p-3 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 dark:text-white">
                <div className="h-1/2 p-1 m-3 border-1 rounded-sm flex justify-center items-center">نما</div>
                <div className="h-1/2 p-1 m-3 border-1 rounded-sm flex justify-center items-center">داخلی</div>
                <div className="h-1/2 p-1 m-3 border-1 rounded-sm flex justify-center items-center">نورپردازی</div>
                <div className="h-1/2 p-1 m-3 border-1 rounded-sm flex justify-center items-center">معماری و طراحی</div>
            </div>

        </>
    )
}


export default Projects