import PagesHeader from "@/components/header-other-pages";
import PagesHeaderTransparent from "@/components/header-other-pages-transparent";
import Image from "next/image";



export const metadata = {
    title: "Introduce of projects",
    description: "Generated by create next app",
};



function Projects() {


    return (
        <>
            <div className="w-full min-h-screen">
                <div className="w-full min-h-screen bg-[url(/images/img/arch2.jpg)] bg-no-repeat bg-cover">
                    <PagesHeaderTransparent />
                </div>
            </div>
        </>
    )
}


export default Projects