

export const metadata = {
    title: "Contact Us",
    description: "Generated by create next app",
};


function Contact() {


    return (
        <>
            <section className="text-center md:mb-2">
                <div className="p-6">
                    <h1 className="text-xl mb-4">تماس با ما</h1>
                    <p className="mb-6">اگر مایل به تماس هستید، لطفا با استفاده از اطلاعات زیر با ما تماس بگیرید.</p>
                </div>

                <div className="flex flex-col items-center p-6 md:flex-row justify-center">
                    <div className="w-1/3 mb-3 md:mb-1">
                        <h2 className="text-lg">آدرس</h2>
                        <p>IRAN-Tehran</p>
                    </div>

                    <div className="w-1/3 mb-3 md:mb-1">
                        <h2 className="text-lg">تلفن تماس</h2>
                        <p>+(98) 933-8487937</p>
                    </div>

                    {/* <div className="w-1/3 mb-3 md:mb-1">
                        <h2 className="text-lg">Address</h2>
                        <p>123 London st, UK</p>
                    </div> */}
                </div>
            </section>
        </>
    )
}


export default Contact